project:
  type: website

website:
  title: "RWorkshop"
  navbar:
    left:
      - text: "R Series"
        menu:
          - text: "Episode"
            href: Hands-on_Ex.html
          - text: "Now You See It"
            href: xxx.html
          - text: "Introduction to QGIS"
            href: xxx.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd
